[workspace.metadata.release]
shared-version = true
consolidate-commits = true
tag-name = "v{{version}}"
publish = false
push = true
allow-branch = ["main"]
sign-tag = false
pre-release-commit-message = "chore(release): {{version}} [skip ci]"